# Code generated by pgdesign -- do not edit.
# This package is generated by `pgdesign codegen --lang python --mode ddl --split-mode faceted`.
# Re-run the codegen command to regenerate; use `pgdesign codegen --check` to verify freshness.
