# Code generated by pgdesign -- do not edit.

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE TABLE public.sources (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    slug text NOT NULL,
    name text NOT NULL,
    credential_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_sources PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.sources (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    slug text NOT NULL,
    name text NOT NULL,
    credential_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_sources PRIMARY KEY (id)
);""", "table", "sources", "sources", 4, True),
    DDLStmt("""CREATE TABLE public.subscriptions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    source_id uuid,
    filter_expr jsonb NOT NULL DEFAULT '{}',
    enabled bool NOT NULL DEFAULT true,
    storage text NOT NULL DEFAULT 'persistent',
    owner_run_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.subscriptions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    source_id uuid,
    filter_expr jsonb NOT NULL DEFAULT '{}',
    enabled bool NOT NULL DEFAULT true,
    storage text NOT NULL DEFAULT 'persistent',
    owner_run_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);""", "table", "subscriptions", "subscriptions", 4, True),
    DDLStmt("""CREATE TABLE public.subscription_actions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    subscription_id uuid NOT NULL,
    position int4 NOT NULL,
    action_type text NOT NULL,
    action_config jsonb NOT NULL DEFAULT '{}',
    accumulator_config jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_subscription_actions PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.subscription_actions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    subscription_id uuid NOT NULL,
    position int4 NOT NULL,
    action_type text NOT NULL,
    action_config jsonb NOT NULL DEFAULT '{}',
    accumulator_config jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_subscription_actions PRIMARY KEY (id)
);""", "table", "subscription_actions", "subscription_actions", 4, True),
    DDLStmt("""CREATE TABLE public.accumulator_buffer (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    subscription_action_id uuid NOT NULL,
    event_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_accumulator_buffer PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.accumulator_buffer (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    subscription_action_id uuid NOT NULL,
    event_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_accumulator_buffer PRIMARY KEY (id)
);""", "table", "accumulator_buffer", "accumulator_buffer", 4, True),
    DDLStmt("ALTER TABLE public.subscriptions ADD CONSTRAINT fk_subscriptions_run FOREIGN KEY (owner_run_id) REFERENCES public.runs (id) ON DELETE SET NULL;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_subscriptions_run'
    AND conrelid = 'public.subscriptions'::regclass
  ) THEN
    ALTER TABLE public.subscriptions ADD CONSTRAINT fk_subscriptions_run FOREIGN KEY (owner_run_id) REFERENCES public.runs (id) ON DELETE SET NULL;
  END IF;
END $$;""", "fk", "fk_subscriptions_run", "subscriptions", 6, True),
    DDLStmt("ALTER TABLE public.subscriptions ADD CONSTRAINT fk_subscriptions_source FOREIGN KEY (source_id) REFERENCES public.sources (id) ON DELETE SET NULL;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_subscriptions_source'
    AND conrelid = 'public.subscriptions'::regclass
  ) THEN
    ALTER TABLE public.subscriptions ADD CONSTRAINT fk_subscriptions_source FOREIGN KEY (source_id) REFERENCES public.sources (id) ON DELETE SET NULL;
  END IF;
END $$;""", "fk", "fk_subscriptions_source", "subscriptions", 6, True),
    DDLStmt("ALTER TABLE public.subscription_actions ADD CONSTRAINT fk_subscription_actions_sub FOREIGN KEY (subscription_id) REFERENCES public.subscriptions (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_subscription_actions_sub'
    AND conrelid = 'public.subscription_actions'::regclass
  ) THEN
    ALTER TABLE public.subscription_actions ADD CONSTRAINT fk_subscription_actions_sub FOREIGN KEY (subscription_id) REFERENCES public.subscriptions (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_subscription_actions_sub", "subscription_actions", 6, True),
    DDLStmt("ALTER TABLE public.accumulator_buffer ADD CONSTRAINT fk_accumulator_buffer_action FOREIGN KEY (subscription_action_id) REFERENCES public.subscription_actions (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_accumulator_buffer_action'
    AND conrelid = 'public.accumulator_buffer'::regclass
  ) THEN
    ALTER TABLE public.accumulator_buffer ADD CONSTRAINT fk_accumulator_buffer_action FOREIGN KEY (subscription_action_id) REFERENCES public.subscription_actions (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_accumulator_buffer_action", "accumulator_buffer", 6, True),
    DDLStmt("ALTER TABLE public.accumulator_buffer ADD CONSTRAINT fk_accumulator_buffer_event FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_accumulator_buffer_event'
    AND conrelid = 'public.accumulator_buffer'::regclass
  ) THEN
    ALTER TABLE public.accumulator_buffer ADD CONSTRAINT fk_accumulator_buffer_event FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_accumulator_buffer_event", "accumulator_buffer", 6, True),
    DDLStmt("ALTER TABLE public.sources ADD CONSTRAINT uq_sources_slug UNIQUE (slug);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_sources_slug'
    AND conrelid = 'public.sources'::regclass
  ) THEN
    ALTER TABLE public.sources ADD CONSTRAINT uq_sources_slug UNIQUE (slug);
  END IF;
END $$;""", "unique", "uq_sources_slug", "sources", 7, True),
    DDLStmt("ALTER TABLE public.subscription_actions ADD CONSTRAINT uq_subscription_actions_position UNIQUE (subscription_id, position);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_subscription_actions_position'
    AND conrelid = 'public.subscription_actions'::regclass
  ) THEN
    ALTER TABLE public.subscription_actions ADD CONSTRAINT uq_subscription_actions_position UNIQUE (subscription_id, position);
  END IF;
END $$;""", "unique", "uq_subscription_actions_position", "subscription_actions", 7, True),
    DDLStmt("ALTER TABLE public.sources ADD CONSTRAINT chk_sources_slug_not_empty CHECK (slug <> '' AND name <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_sources_slug_not_empty'
    AND conrelid = 'public.sources'::regclass
  ) THEN
    ALTER TABLE public.sources ADD CONSTRAINT chk_sources_slug_not_empty CHECK (slug <> '' AND name <> '');
  END IF;
END $$;""", "check", "chk_sources_slug_not_empty", "sources", 8, True),
    DDLStmt("ALTER TABLE public.subscriptions ADD CONSTRAINT chk_subscriptions_storage_valid CHECK (storage IN ('persistent', 'transient'));", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_subscriptions_storage_valid'
    AND conrelid = 'public.subscriptions'::regclass
  ) THEN
    ALTER TABLE public.subscriptions ADD CONSTRAINT chk_subscriptions_storage_valid CHECK (storage IN ('persistent', 'transient'));
  END IF;
END $$;""", "check", "chk_subscriptions_storage_valid", "subscriptions", 8, True),
    DDLStmt("ALTER TABLE public.subscription_actions ADD CONSTRAINT chk_subscription_actions_position_positive CHECK (position >= 0 AND action_type <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_subscription_actions_position_positive'
    AND conrelid = 'public.subscription_actions'::regclass
  ) THEN
    ALTER TABLE public.subscription_actions ADD CONSTRAINT chk_subscription_actions_position_positive CHECK (position >= 0 AND action_type <> '');
  END IF;
END $$;""", "check", "chk_subscription_actions_position_positive", "subscription_actions", 8, True),
    DDLStmt("ALTER TABLE public.accumulator_buffer ADD CONSTRAINT chk_accumulator_buffer_refs_not_null CHECK (subscription_action_id IS NOT NULL AND event_id IS NOT NULL);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_accumulator_buffer_refs_not_null'
    AND conrelid = 'public.accumulator_buffer'::regclass
  ) THEN
    ALTER TABLE public.accumulator_buffer ADD CONSTRAINT chk_accumulator_buffer_refs_not_null CHECK (subscription_action_id IS NOT NULL AND event_id IS NOT NULL);
  END IF;
END $$;""", "check", "chk_accumulator_buffer_refs_not_null", "accumulator_buffer", 8, True),
    DDLStmt("CREATE INDEX idx_subscriptions_active ON public.subscriptions (source_id, created_at) WHERE enabled = true;", "CREATE INDEX IF NOT EXISTS idx_subscriptions_active ON public.subscriptions (source_id, created_at) WHERE enabled = true;", "index", "idx_subscriptions_active", "subscriptions", 9, True),
    DDLStmt("CREATE INDEX idx_subscriptions_filter_expr_gin ON public.subscriptions USING gin (filter_expr);", "CREATE INDEX IF NOT EXISTS idx_subscriptions_filter_expr_gin ON public.subscriptions USING gin (filter_expr);", "index", "idx_subscriptions_filter_expr_gin", "subscriptions", 9, True),
    DDLStmt("CREATE INDEX idx_subscriptions_owner_run_id ON public.subscriptions (owner_run_id);", "CREATE INDEX IF NOT EXISTS idx_subscriptions_owner_run_id ON public.subscriptions (owner_run_id);", "index", "idx_subscriptions_owner_run_id", "subscriptions", 9, True),
    DDLStmt("CREATE INDEX idx_subscription_actions_accumulator_gin ON public.subscription_actions USING gin (accumulator_config);", "CREATE INDEX IF NOT EXISTS idx_subscription_actions_accumulator_gin ON public.subscription_actions USING gin (accumulator_config);", "index", "idx_subscription_actions_accumulator_gin", "subscription_actions", 9, True),
    DDLStmt("CREATE INDEX idx_subscription_actions_config_gin ON public.subscription_actions USING gin (action_config);", "CREATE INDEX IF NOT EXISTS idx_subscription_actions_config_gin ON public.subscription_actions USING gin (action_config);", "index", "idx_subscription_actions_config_gin", "subscription_actions", 9, True),
    DDLStmt("CREATE INDEX idx_subscription_actions_sub ON public.subscription_actions (subscription_id);", "CREATE INDEX IF NOT EXISTS idx_subscription_actions_sub ON public.subscription_actions (subscription_id);", "index", "idx_subscription_actions_sub", "subscription_actions", 9, True),
    DDLStmt("CREATE INDEX idx_accumulator_buffer_action ON public.accumulator_buffer (subscription_action_id);", "CREATE INDEX IF NOT EXISTS idx_accumulator_buffer_action ON public.accumulator_buffer (subscription_action_id);", "index", "idx_accumulator_buffer_action", "accumulator_buffer", 9, True),
    DDLStmt("CREATE INDEX idx_accumulator_buffer_event ON public.accumulator_buffer (event_id);", "CREATE INDEX IF NOT EXISTS idx_accumulator_buffer_event ON public.accumulator_buffer (event_id);", "index", "idx_accumulator_buffer_event", "accumulator_buffer", 9, True),
    DDLStmt("COMMENT ON TABLE public.sources IS 'Registry of event sources (webhook endpoints, polled APIs, internal emitters).';", None, "comment", "table.sources", "sources", 10, True),
    DDLStmt("COMMENT ON COLUMN public.sources.slug IS 'URL-safe unique identifier';", None, "comment", "column.sources.slug", "sources", 10, True),
    DDLStmt("COMMENT ON COLUMN public.sources.name IS 'Human-readable source name';", None, "comment", "column.sources.name", "sources", 10, True),
    DDLStmt("COMMENT ON COLUMN public.sources.credential_id IS 'FK to auth.credentials for source authentication';", None, "comment", "column.sources.credential_id", "sources", 10, True),
    DDLStmt("COMMENT ON TABLE public.subscriptions IS 'Event subscriptions. A subscription matches events via filter_expr and routes them to actions.';", None, "comment", "table.subscriptions", "subscriptions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscriptions.source_id IS 'Optional source filter (null = match all sources)';", None, "comment", "column.subscriptions.source_id", "subscriptions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscriptions.filter_expr IS 'FilterPredicate serialized as JSON';", None, "comment", "column.subscriptions.filter_expr", "subscriptions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscriptions.storage IS 'Storage mode: persistent or transient';", None, "comment", "column.subscriptions.storage", "subscriptions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscriptions.owner_run_id IS 'Run that owns this subscription (null = global)';", None, "comment", "column.subscriptions.owner_run_id", "subscriptions", 10, True),
    DDLStmt("COMMENT ON TABLE public.subscription_actions IS 'Ordered action pipeline for a subscription. Each action processes matched events.';", None, "comment", "table.subscription_actions", "subscription_actions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscription_actions.position IS 'Execution order within the subscription';", None, "comment", "column.subscription_actions.position", "subscription_actions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscription_actions.action_type IS 'Action type identifier (e.g. script, log, webhook)';", None, "comment", "column.subscription_actions.action_type", "subscription_actions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscription_actions.action_config IS 'Action-specific configuration';", None, "comment", "column.subscription_actions.action_config", "subscription_actions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.subscription_actions.accumulator_config IS 'Accumulator settings (batch size, flush interval, etc.)';", None, "comment", "column.subscription_actions.accumulator_config", "subscription_actions", 10, True),
    DDLStmt("COMMENT ON TABLE public.accumulator_buffer IS 'Buffered events awaiting batch delivery for accumulator-enabled actions.';", None, "comment", "table.accumulator_buffer", "accumulator_buffer", 10, True),
    DDLStmt("COMMENT ON COLUMN public.accumulator_buffer.event_id IS 'Reference to the trace events table';", None, "comment", "column.accumulator_buffer.event_id", "accumulator_buffer", 10, True),
]

TABLE_NAMES: Final[tuple[str, ...]] = ("sources", "subscriptions", "subscription_actions", "accumulator_buffer")
