# Code generated by pgdesign -- do not edit.

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("CREATE TYPE public.run_status AS ENUM ('created', 'running', 'paused', 'completed', 'failed', 'aborted');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'run_status' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.run_status AS ENUM (''created'', ''running'', ''paused'', ''completed'', ''failed'', ''aborted'');';
  END IF;
END $$;""", "enum", "run_status", None, 3, True),
    DDLStmt("CREATE TYPE public.task_state AS ENUM ('created', 'prechecking', 'active', 'postchecking', 'completed', 'precheck_failed', 'postcheck_failed', 'escalated', 'cancelled');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'task_state' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.task_state AS ENUM (''created'', ''prechecking'', ''active'', ''postchecking'', ''completed'', ''precheck_failed'', ''postcheck_failed'', ''escalated'', ''cancelled'');';
  END IF;
END $$;""", "enum", "task_state", None, 3, True),
    DDLStmt("CREATE TYPE public.attempt_status AS ENUM ('running', 'completed', 'failed');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'attempt_status' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.attempt_status AS ENUM (''running'', ''completed'', ''failed'');';
  END IF;
END $$;""", "enum", "attempt_status", None, 3, True),
    DDLStmt("CREATE TYPE public.task_type AS ENUM ('agent', 'callable', 'workflow', 'decision_point', 'wait_for');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'task_type' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.task_type AS ENUM (''agent'', ''callable'', ''workflow'', ''decision_point'', ''wait_for'');';
  END IF;
END $$;""", "enum", "task_type", None, 3, True),
    DDLStmt("CREATE TYPE public.entry_type AS ENUM ('learning', 'decision', 'issue');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'entry_type' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.entry_type AS ENUM (''learning'', ''decision'', ''issue'');';
  END IF;
END $$;""", "enum", "entry_type", None, 3, True),
    DDLStmt("CREATE TYPE public.inbox_status AS ENUM ('pending', 'answered', 'skipped', 'expired', 'rejected');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'inbox_status' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.inbox_status AS ENUM (''pending'', ''answered'', ''skipped'', ''expired'', ''rejected'');';
  END IF;
END $$;""", "enum", "inbox_status", None, 3, True),
    DDLStmt("CREATE TYPE public.constraint_tier AS ENUM ('mechanical', 'advisory');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'constraint_tier' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.constraint_tier AS ENUM (''mechanical'', ''advisory'');';
  END IF;
END $$;""", "enum", "constraint_tier", None, 3, True),
    DDLStmt("CREATE TYPE public.assumption_scope AS ENUM ('understanding', 'decomposition', 'task');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'assumption_scope' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.assumption_scope AS ENUM (''understanding'', ''decomposition'', ''task'');';
  END IF;
END $$;""", "enum", "assumption_scope", None, 3, True),
    DDLStmt("CREATE TYPE public.autonomy_level AS ENUM ('low', 'medium', 'high', 'max');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'autonomy_level' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.autonomy_level AS ENUM (''low'', ''medium'', ''high'', ''max'');';
  END IF;
END $$;""", "enum", "autonomy_level", None, 3, True),
    DDLStmt("CREATE TYPE public.workflow_health AS ENUM ('healthy', 'degraded', 'failing');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'workflow_health' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.workflow_health AS ENUM (''healthy'', ''degraded'', ''failing'');';
  END IF;
END $$;""", "enum", "workflow_health", None, 3, True),
    DDLStmt("CREATE TYPE public.trust_tier AS ENUM ('anonymous', 'identified', 'verified', 'system');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'trust_tier' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.trust_tier AS ENUM (''anonymous'', ''identified'', ''verified'', ''system'');';
  END IF;
END $$;""", "enum", "trust_tier", None, 3, True),
    DDLStmt("CREATE TYPE public.credential_type AS ENUM ('api_key', 'bearer');", """DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'credential_type' AND n.nspname = 'public' AND t.typtype = 'e') THEN
    EXECUTE 'CREATE TYPE public.credential_type AS ENUM (''api_key'', ''bearer'');';
  END IF;
END $$;""", "enum", "credential_type", None, 3, True),
]
