# Code generated by pgdesign. DO NOT EDIT.
# pgdesign-revision: registry_present:5bbb0fef5368f47b9ae623f400572606bc0f8a84bda125f174270f86cf856f9a

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("CREATE SCHEMA public;", "CREATE SCHEMA IF NOT EXISTS public;", "schema", "public", None, 1, True),
    DDLStmt("""CREATE OR REPLACE FUNCTION public.pgdesign_deny_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'table % is append-only: UPDATE and DELETE are not allowed', TG_TABLE_NAME;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;""", """CREATE OR REPLACE FUNCTION public.pgdesign_deny_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'table % is append-only: UPDATE and DELETE are not allowed', TG_TABLE_NAME;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;""", "append_only_trigger", "public.pgdesign_deny_mutation", None, 9, True),
]
