# Code generated by pgdesign. DO NOT EDIT.
# pgdesign-revision: registry_present:5bbb0fef5368f47b9ae623f400572606bc0f8a84bda125f174270f86cf856f9a

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE TABLE public.notification_deliveries (
    id uuid NOT NULL DEFAULT uuidv7(),
    target_principal_id uuid NOT NULL,
    source_ref text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    acknowledged_at timestamptz,
    CONSTRAINT pk_notification_deliveries PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.notification_deliveries (
    id uuid NOT NULL DEFAULT uuidv7(),
    target_principal_id uuid NOT NULL,
    source_ref text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    acknowledged_at timestamptz,
    CONSTRAINT pk_notification_deliveries PRIMARY KEY (id)
);""", "table", "notification_deliveries", "notification_deliveries", 4, True),
    DDLStmt("ALTER TABLE public.notification_deliveries ADD CONSTRAINT fk_notification_deliveries_target_principal FOREIGN KEY (target_principal_id) REFERENCES public.principals (id) ON DELETE RESTRICT;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_notification_deliveries_target_principal'
    AND conrelid = 'public.notification_deliveries'::regclass
  ) THEN
    ALTER TABLE public.notification_deliveries ADD CONSTRAINT fk_notification_deliveries_target_principal FOREIGN KEY (target_principal_id) REFERENCES public.principals (id) ON DELETE RESTRICT;
  END IF;
END $$;""", "fk", "fk_notification_deliveries_target_principal", "notification_deliveries", 6, True),
    DDLStmt("ALTER TABLE public.notification_deliveries ADD CONSTRAINT chk_notification_deliveries_source_ref_not_empty CHECK (source_ref <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_notification_deliveries_source_ref_not_empty'
    AND conrelid = 'public.notification_deliveries'::regclass
  ) THEN
    ALTER TABLE public.notification_deliveries ADD CONSTRAINT chk_notification_deliveries_source_ref_not_empty CHECK (source_ref <> '');
  END IF;
END $$;""", "check", "chk_notification_deliveries_source_ref_not_empty", "notification_deliveries", 8, True),
    DDLStmt("CREATE INDEX idx_notification_deliveries_source_ref ON public.notification_deliveries (source_ref);", "CREATE INDEX IF NOT EXISTS idx_notification_deliveries_source_ref ON public.notification_deliveries (source_ref);", "index", "idx_notification_deliveries_source_ref", "notification_deliveries", 9, True),
    DDLStmt("CREATE INDEX idx_notification_deliveries_unacked ON public.notification_deliveries (target_principal_id, created_at) WHERE acknowledged_at IS NULL;", "CREATE INDEX IF NOT EXISTS idx_notification_deliveries_unacked ON public.notification_deliveries (target_principal_id, created_at) WHERE acknowledged_at IS NULL;", "index", "idx_notification_deliveries_unacked", "notification_deliveries", 9, True),
    DDLStmt("COMMENT ON TABLE public.notification_deliveries IS 'Persisted notifications targeting specific principals. INSERT fires PG NOTIFY for real-time pickup.';", None, "comment", "table.notification_deliveries", "notification_deliveries", 10, True),
    DDLStmt("COMMENT ON COLUMN public.notification_deliveries.target_principal_id IS 'The principal this notification is addressed to.';", None, "comment", "column.notification_deliveries.target_principal_id", "notification_deliveries", 10, True),
    DDLStmt("COMMENT ON COLUMN public.notification_deliveries.source_ref IS 'Opaque reference string describing the origin (e.g. ''self-subscription'', ''event:run_completed:UUID''). No upward FK.';", None, "comment", "column.notification_deliveries.source_ref", "notification_deliveries", 10, True),
    DDLStmt("COMMENT ON COLUMN public.notification_deliveries.payload IS 'Notification content';", None, "comment", "column.notification_deliveries.payload", "notification_deliveries", 10, True),
    DDLStmt("CREATE TRIGGER trg_notify_notification_delivery AFTER INSERT ON public.notification_deliveries FOR EACH ROW EXECUTE FUNCTION public.notify_orxtra_notification();", "CREATE OR REPLACE TRIGGER trg_notify_notification_delivery AFTER INSERT ON public.notification_deliveries FOR EACH ROW EXECUTE FUNCTION public.notify_orxtra_notification();", "trigger", "trg_notify_notification_delivery", "notification_deliveries", 17, True),
]

TABLE_NAMES: Final[tuple[str, ...]] = ("notification_deliveries",)
