# Code generated by pgdesign. DO NOT EDIT.
# pgdesign-revision: registry_present:5bbb0fef5368f47b9ae623f400572606bc0f8a84bda125f174270f86cf856f9a

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE TABLE public.principals (
    id uuid NOT NULL DEFAULT uuidv7(),
    kind text NOT NULL,
    external_ref uuid NOT NULL,
    display_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_principals PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.principals (
    id uuid NOT NULL DEFAULT uuidv7(),
    kind text NOT NULL,
    external_ref uuid NOT NULL,
    display_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_principals PRIMARY KEY (id)
);""", "table", "principals", "principals", 4, True),
    DDLStmt("ALTER TABLE public.principals ADD CONSTRAINT uq_principals_kind_external_ref UNIQUE (kind, external_ref);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_principals_kind_external_ref'
    AND conrelid = 'public.principals'::regclass
  ) THEN
    ALTER TABLE public.principals ADD CONSTRAINT uq_principals_kind_external_ref UNIQUE (kind, external_ref);
  END IF;
END $$;""", "unique", "uq_principals_kind_external_ref", "principals", 7, True),
    DDLStmt("COMMENT ON TABLE public.principals IS 'Actors that can own or perform actions. FK target for other modules; never a user-profile store.';", None, "comment", "table.principals", "principals", 10, True),
    DDLStmt("COMMENT ON COLUMN public.principals.kind IS 'Actor kind, registered at composition time; built-ins are run/consumer/source/system. Validation lives at the service layer -- storage accepts any string.';", None, "comment", "column.principals.kind", "principals", 10, True),
    DDLStmt("COMMENT ON COLUMN public.principals.external_ref IS 'The actor''s id in its kind''s namespace; for the singleton system principal this is the all-zeros sentinel.';", None, "comment", "column.principals.external_ref", "principals", 10, True),
    DDLStmt("COMMENT ON COLUMN public.principals.display_name IS 'Optional human-readable label for the actor';", None, "comment", "column.principals.display_name", "principals", 10, True),
]

TABLE_NAMES: Final[tuple[str, ...]] = ("principals",)
