from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("orxtra-trace")
except PackageNotFoundError:
    __version__ = "0.0.0"

from orxtra.trace._lock import (
    RunLockError,
    acquire_run_lock,
    is_lock_stale,
    lock_key,
    release_run_lock,
    update_heartbeat,
)
from orxtra.trace._memory_backend import InMemoryBackend, InMemoryEventBus
from orxtra.trace._pg_backend import PgBackend
from orxtra.trace._pg_event_bus import PgEventBus
from orxtra.trace._protocols import (
    EventBus,
    EventStorage,
    InboxStorage,
    KnowledgeHashStorage,
    NotepadStorage,
    OverseerStorage,
    RecoveryOperations,
    RunControlStorage,
    RunStorage,
    StorageBackend,
    StorageLock,
    StorageReader,
    TaskStorage,
)
from orxtra.trace._reader import (
    list_iterations,
    list_runs,
    list_tasks,
    query_events,
    query_lessons,
    query_relevant_lessons,
    read_active_constraints,
    read_assumptions,
    read_constraints,
    read_decisions,
    read_inbox,
    read_inbox_item,
    read_latest_attempt,
    read_notepad,
    read_run_config,
    read_run_report,
    read_session_token_counts,
    read_session_turn_count,
    read_task_attempt,
    read_task_attempts,
    read_transcript,
    read_workflow_status,
    replay,
    search_transcript,
)
from orxtra.trace._recovery import (
    clean_orphaned,
    reclaim_interrupted,
    reevaluate_blocked,
)
from orxtra.trace._transitions import (
    InvalidTransitionError,
    validate_run_transition,
    validate_task_transition,
)
from orxtra.trace._types import (
    InboxItem,
    IterationResult,
    NotepadEntry,
    RunReport,
    RunSummary,
    TaskAttempt,
    TaskSummary,
)
from orxtra.trace._trace_sink import TraceSink
from orxtra.trace._writer import TraceWriter

# The PG NOTIFY channel used by the events trigger. Authoritative constant;
# all code that subscribes or publishes on this channel must use it.
EVENTS_CHANNEL: str = "orxtra_events"

# TABLE_NAMES: authoritative list of trace-owned tables.
# Source of truth is schema/trace.toml; this tuple matches tables_trace.py
# generated by pgdesign codegen. The DDL execution itself is handled by
# schema/_generated/schema_executor.py (replaces the old ALL_CREATE_STATEMENTS).
TABLE_NAMES: tuple[str, ...] = (
    "assumptions",
    "constraints",
    "context_diffs",
    "decisions",
    "events",
    "inbox_items",
    "knowledge_hashes",
    "lessons",
    "notepad_entries",
    "overseer_workflow_status",
    "run_heartbeats",
    "runs",
    "task_attempts",
    "task_iterations",
    "tasks",
    "transcripts",
)

__all__ = [
    "EVENTS_CHANNEL",
    "TABLE_NAMES",
    "__version__",
    "EventBus",
    "EventStorage",
    "InMemoryBackend",
    "InMemoryEventBus",
    "InboxItem",
    "InboxStorage",
    "InvalidTransitionError",
    "KnowledgeHashStorage",
    "IterationResult",
    "NotepadEntry",
    "NotepadStorage",
    "OverseerStorage",
    "PgBackend",
    "PgEventBus",
    "RecoveryOperations",
    "RunControlStorage",
    "RunLockError",
    "RunReport",
    "RunStorage",
    "RunSummary",
    "StorageBackend",
    "StorageLock",
    "StorageReader",
    "TaskAttempt",
    "TaskStorage",
    "TaskSummary",
    "TraceSink",
    "TraceWriter",
    "acquire_run_lock",
    "clean_orphaned",
    "is_lock_stale",
    "list_iterations",
    "list_runs",
    "lock_key",
    "list_tasks",
    "query_events",
    "query_lessons",
    "query_relevant_lessons",
    "read_active_constraints",
    "read_assumptions",
    "read_constraints",
    "read_decisions",
    "read_inbox",
    "read_inbox_item",
    "read_latest_attempt",
    "read_notepad",
    "read_run_config",
    "read_run_report",
    "read_session_token_counts",
    "read_session_turn_count",
    "read_task_attempt",
    "read_task_attempts",
    "read_transcript",
    "read_workflow_status",
    "reclaim_interrupted",
    "replay",
    "reevaluate_blocked",
    "release_run_lock",
    "search_transcript",
    "update_heartbeat",
    "validate_run_transition",
    "validate_task_transition",
]
