# Code generated by pgdesign -- do not edit.

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("CREATE SCHEMA public;", "CREATE SCHEMA IF NOT EXISTS public;", "schema", "public", None, 1, True),
    DDLStmt("CREATE EXTENSION pg_uuidv7;", "CREATE EXTENSION IF NOT EXISTS pg_uuidv7;", "extension", "pg_uuidv7", None, 2, True),
    DDLStmt("""CREATE OR REPLACE FUNCTION public.pgdesign_deny_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'table % is append-only: UPDATE and DELETE are not allowed', TG_TABLE_NAME;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;""", """CREATE OR REPLACE FUNCTION public.pgdesign_deny_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'table % is append-only: UPDATE and DELETE are not allowed', TG_TABLE_NAME;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;""", "append_only_trigger", "public.pgdesign_deny_mutation", None, 9, True),
]
