# Code generated by pgdesign -- do not edit.

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE OR REPLACE FUNCTION public.notify_orxtra_event()
RETURNS trigger
AS $pgdesign$
BEGIN
    PERFORM pg_notify('orxtra_events', json_build_object(
        'event_id', NEW.id,
        'run_id', NEW.run_id,
        'principal_id', NEW.principal_id::text,
        'event_type', NEW.event_type
    )::text);
    RETURN NEW;
END;

$pgdesign$
LANGUAGE plpgsql;""", """CREATE OR REPLACE FUNCTION public.notify_orxtra_event()
RETURNS trigger
AS $pgdesign$
BEGIN
    PERFORM pg_notify('orxtra_events', json_build_object(
        'event_id', NEW.id,
        'run_id', NEW.run_id,
        'principal_id', NEW.principal_id::text,
        'event_type', NEW.event_type
    )::text);
    RETURN NEW;
END;

$pgdesign$
LANGUAGE plpgsql;""", "function", "notify_orxtra_event", None, 16, True),
]
