# Code generated by pgdesign. DO NOT EDIT.
# pgdesign-revision: registry_present:5bbb0fef5368f47b9ae623f400572606bc0f8a84bda125f174270f86cf856f9a

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE OR REPLACE FUNCTION public.notify_orxtra_event()
RETURNS trigger
AS $pgdesign$
BEGIN
    PERFORM pg_notify('orxtra_events', json_build_object(
        'event_id', NEW.id,
        'run_id', NEW.run_id,
        'principal_id', NEW.principal_id::text,
        'event_type', NEW.event_type
    )::text);
    RETURN NEW;
END;

$pgdesign$
LANGUAGE plpgsql;""", """CREATE OR REPLACE FUNCTION public.notify_orxtra_event()
RETURNS trigger
AS $pgdesign$
BEGIN
    PERFORM pg_notify('orxtra_events', json_build_object(
        'event_id', NEW.id,
        'run_id', NEW.run_id,
        'principal_id', NEW.principal_id::text,
        'event_type', NEW.event_type
    )::text);
    RETURN NEW;
END;

$pgdesign$
LANGUAGE plpgsql;""", "function", "notify_orxtra_event", None, 16, True),
    DDLStmt("""CREATE OR REPLACE FUNCTION public.notify_orxtra_notification()
RETURNS trigger
AS $pgdesign$
BEGIN
    PERFORM pg_notify('orxtra_notifications', json_build_object(
        'notification_id', NEW.id,
        'target_principal_id', NEW.target_principal_id::text
    )::text);
    RETURN NEW;
END;

$pgdesign$
LANGUAGE plpgsql;""", """CREATE OR REPLACE FUNCTION public.notify_orxtra_notification()
RETURNS trigger
AS $pgdesign$
BEGIN
    PERFORM pg_notify('orxtra_notifications', json_build_object(
        'notification_id', NEW.id,
        'target_principal_id', NEW.target_principal_id::text
    )::text);
    RETURN NEW;
END;

$pgdesign$
LANGUAGE plpgsql;""", "function", "notify_orxtra_notification", None, 16, True),
]
