# Code generated by pgdesign -- do not edit.

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE TABLE public.consumers (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    name text NOT NULL,
    trust_tier public.trust_tier NOT NULL,
    scope_grants jsonb NOT NULL DEFAULT '[]',
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_consumers PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.consumers (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    name text NOT NULL,
    trust_tier public.trust_tier NOT NULL,
    scope_grants jsonb NOT NULL DEFAULT '[]',
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_consumers PRIMARY KEY (id)
);""", "table", "consumers", "consumers", 4, True),
    DDLStmt("""CREATE TABLE public.credentials (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    consumer_id uuid NOT NULL,
    credential_type public.credential_type NOT NULL,
    credential_hash text NOT NULL,
    algorithm text NOT NULL DEFAULT 'sha256',
    metadata jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_credentials PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.credentials (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    consumer_id uuid NOT NULL,
    credential_type public.credential_type NOT NULL,
    credential_hash text NOT NULL,
    algorithm text NOT NULL DEFAULT 'sha256',
    metadata jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_credentials PRIMARY KEY (id)
);""", "table", "credentials", "credentials", 4, True),
    DDLStmt("ALTER TABLE public.credentials ADD CONSTRAINT fk_credentials_consumer FOREIGN KEY (consumer_id) REFERENCES public.consumers (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_credentials_consumer'
    AND conrelid = 'public.credentials'::regclass
  ) THEN
    ALTER TABLE public.credentials ADD CONSTRAINT fk_credentials_consumer FOREIGN KEY (consumer_id) REFERENCES public.consumers (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_credentials_consumer", "credentials", 6, True),
    DDLStmt("ALTER TABLE public.consumers ADD CONSTRAINT chk_consumers_name_not_empty CHECK (name <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_consumers_name_not_empty'
    AND conrelid = 'public.consumers'::regclass
  ) THEN
    ALTER TABLE public.consumers ADD CONSTRAINT chk_consumers_name_not_empty CHECK (name <> '');
  END IF;
END $$;""", "check", "chk_consumers_name_not_empty", "consumers", 8, True),
    DDLStmt("ALTER TABLE public.credentials ADD CONSTRAINT chk_credentials_hash_not_empty CHECK (credential_hash <> '' AND algorithm <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_credentials_hash_not_empty'
    AND conrelid = 'public.credentials'::regclass
  ) THEN
    ALTER TABLE public.credentials ADD CONSTRAINT chk_credentials_hash_not_empty CHECK (credential_hash <> '' AND algorithm <> '');
  END IF;
END $$;""", "check", "chk_credentials_hash_not_empty", "credentials", 8, True),
    DDLStmt("CREATE INDEX idx_consumers_scope_grants_gin ON public.consumers USING gin (scope_grants);", "CREATE INDEX IF NOT EXISTS idx_consumers_scope_grants_gin ON public.consumers USING gin (scope_grants);", "index", "idx_consumers_scope_grants_gin", "consumers", 9, True),
    DDLStmt("CREATE INDEX idx_credentials_consumer_id ON public.credentials (consumer_id);", "CREATE INDEX IF NOT EXISTS idx_credentials_consumer_id ON public.credentials (consumer_id);", "index", "idx_credentials_consumer_id", "credentials", 9, True),
    DDLStmt("CREATE INDEX idx_credentials_hash ON public.credentials (credential_hash);", "CREATE INDEX IF NOT EXISTS idx_credentials_hash ON public.credentials (credential_hash);", "index", "idx_credentials_hash", "credentials", 9, True),
    DDLStmt("CREATE INDEX idx_credentials_metadata_gin ON public.credentials USING gin (metadata);", "CREATE INDEX IF NOT EXISTS idx_credentials_metadata_gin ON public.credentials USING gin (metadata);", "index", "idx_credentials_metadata_gin", "credentials", 9, True),
    DDLStmt("COMMENT ON TABLE public.consumers IS 'API consumers with trust tiers and scope grants.';", None, "comment", "table.consumers", "consumers", 10, True),
    DDLStmt("COMMENT ON COLUMN public.consumers.name IS 'Human-readable consumer name';", None, "comment", "column.consumers.name", "consumers", 10, True),
    DDLStmt("COMMENT ON COLUMN public.consumers.scope_grants IS 'JSON array of granted scope strings';", None, "comment", "column.consumers.scope_grants", "consumers", 10, True),
    DDLStmt("COMMENT ON COLUMN public.consumers.disabled_at IS 'Non-null means the consumer is disabled';", None, "comment", "column.consumers.disabled_at", "consumers", 10, True),
    DDLStmt("COMMENT ON TABLE public.credentials IS 'Hashed credentials linked to consumers.';", None, "comment", "table.credentials", "credentials", 10, True),
    DDLStmt("COMMENT ON COLUMN public.credentials.credential_hash IS 'SHA-256 hash of the raw credential value';", None, "comment", "column.credentials.credential_hash", "credentials", 10, True),
    DDLStmt("COMMENT ON COLUMN public.credentials.algorithm IS 'Hash algorithm used';", None, "comment", "column.credentials.algorithm", "credentials", 10, True),
    DDLStmt("COMMENT ON COLUMN public.credentials.metadata IS 'Additional credential metadata';", None, "comment", "column.credentials.metadata", "credentials", 10, True),
]

TABLE_NAMES: Final[tuple[str, ...]] = ("consumers", "credentials")
