# Code generated by pgdesign -- do not edit.

from typing import Final

from collections import namedtuple

DDLStmt = namedtuple("DDLStmt", ["sql", "idempotent_sql", "kind", "name", "table", "phase", "transactional"])

STATEMENTS: Final[list[DDLStmt]] = [
    DDLStmt("""CREATE TABLE public.runs (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    intent text NOT NULL,
    status public.run_status NOT NULL DEFAULT 'created',
    autonomy_level public.autonomy_level NOT NULL,
    config_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    total_input_tokens int8 NOT NULL DEFAULT 0,
    total_output_tokens int8 NOT NULL DEFAULT 0,
    total_reasoning_tokens int8 NOT NULL DEFAULT 0,
    total_cache_read_tokens int8 NOT NULL DEFAULT 0,
    total_cache_write_tokens int8 NOT NULL DEFAULT 0,
    total_cost_usd numeric(12,6) NOT NULL DEFAULT '0',
    coherence_summary text,
    CONSTRAINT pk_runs PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.runs (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    intent text NOT NULL,
    status public.run_status NOT NULL DEFAULT 'created',
    autonomy_level public.autonomy_level NOT NULL,
    config_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    total_input_tokens int8 NOT NULL DEFAULT 0,
    total_output_tokens int8 NOT NULL DEFAULT 0,
    total_reasoning_tokens int8 NOT NULL DEFAULT 0,
    total_cache_read_tokens int8 NOT NULL DEFAULT 0,
    total_cache_write_tokens int8 NOT NULL DEFAULT 0,
    total_cost_usd numeric(12,6) NOT NULL DEFAULT '0',
    coherence_summary text,
    CONSTRAINT pk_runs PRIMARY KEY (id)
);""", "table", "runs", "runs", 4, True),
    DDLStmt("""CREATE TABLE public.tasks (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    parent_task_id uuid,
    name text NOT NULL,
    task_type public.task_type NOT NULL,
    status public.task_state NOT NULL DEFAULT 'created',
    config jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.tasks (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    parent_task_id uuid,
    name text NOT NULL,
    task_type public.task_type NOT NULL,
    status public.task_state NOT NULL DEFAULT 'created',
    config jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);""", "table", "tasks", "tasks", 4, True),
    DDLStmt("""CREATE TABLE public.transcripts (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    session_id uuid NOT NULL,
    run_id uuid NOT NULL,
    turn int4 NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    tool_calls jsonb,
    tokens jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_transcripts PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.transcripts (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    session_id uuid NOT NULL,
    run_id uuid NOT NULL,
    turn int4 NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    tool_calls jsonb,
    tokens jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_transcripts PRIMARY KEY (id)
);""", "table", "transcripts", "transcripts", 4, True),
    DDLStmt("""CREATE TABLE public.notepad_entries (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    task_name text NOT NULL,
    agent_name text NOT NULL,
    entry_type public.entry_type NOT NULL,
    text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_notepad_entries PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.notepad_entries (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    task_name text NOT NULL,
    agent_name text NOT NULL,
    entry_type public.entry_type NOT NULL,
    text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_notepad_entries PRIMARY KEY (id)
);""", "table", "notepad_entries", "notepad_entries", 4, True),
    DDLStmt("""CREATE TABLE public.inbox_items (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    status public.inbox_status NOT NULL DEFAULT 'pending',
    decision_type text NOT NULL,
    question text NOT NULL,
    options jsonb NOT NULL DEFAULT '[]',
    assumed_option text,
    work_proceeding text,
    contradiction_impact text,
    tags jsonb NOT NULL DEFAULT '[]',
    deadline timestamptz,
    answer text,
    answer_event text,
    rejection_reason text,
    answered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_inbox_items PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.inbox_items (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    status public.inbox_status NOT NULL DEFAULT 'pending',
    decision_type text NOT NULL,
    question text NOT NULL,
    options jsonb NOT NULL DEFAULT '[]',
    assumed_option text,
    work_proceeding text,
    contradiction_impact text,
    tags jsonb NOT NULL DEFAULT '[]',
    deadline timestamptz,
    answer text,
    answer_event text,
    rejection_reason text,
    answered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_inbox_items PRIMARY KEY (id)
);""", "table", "inbox_items", "inbox_items", 4, True),
    DDLStmt("""CREATE TABLE public.decisions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    decision_type text NOT NULL,
    choice text NOT NULL,
    rationale text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_decisions PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.decisions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    decision_type text NOT NULL,
    choice text NOT NULL,
    rationale text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_decisions PRIMARY KEY (id)
);""", "table", "decisions", "decisions", 4, True),
    DDLStmt("""CREATE TABLE public.constraints (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    text text NOT NULL,
    tier public.constraint_tier NOT NULL,
    kind text NOT NULL,
    args jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_constraints PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.constraints (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    text text NOT NULL,
    tier public.constraint_tier NOT NULL,
    kind text NOT NULL,
    args jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_constraints PRIMARY KEY (id)
);""", "table", "constraints", "constraints", 4, True),
    DDLStmt("""CREATE TABLE public.lessons (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    text text NOT NULL,
    relevance_tags jsonb NOT NULL DEFAULT '[]',
    permanent bool NOT NULL DEFAULT false,
    source_files jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.lessons (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    text text NOT NULL,
    relevance_tags jsonb NOT NULL DEFAULT '[]',
    permanent bool NOT NULL DEFAULT false,
    source_files jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);""", "table", "lessons", "lessons", 4, True),
    DDLStmt("""CREATE TABLE public.run_heartbeats (
    run_id uuid NOT NULL,
    last_heartbeat timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_run_heartbeats PRIMARY KEY (run_id)
);""", """CREATE TABLE IF NOT EXISTS public.run_heartbeats (
    run_id uuid NOT NULL,
    last_heartbeat timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_run_heartbeats PRIMARY KEY (run_id)
);""", "table", "run_heartbeats", "run_heartbeats", 4, True),
    DDLStmt("""CREATE TABLE public.knowledge_hashes (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    path text NOT NULL,
    file_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_knowledge_hashes PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.knowledge_hashes (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    path text NOT NULL,
    file_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_knowledge_hashes PRIMARY KEY (id)
);""", "table", "knowledge_hashes", "knowledge_hashes", 4, True),
    DDLStmt("""CREATE TABLE public.task_attempts (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    task_id uuid NOT NULL,
    attempt int4 NOT NULL,
    status public.attempt_status NOT NULL DEFAULT 'running',
    agent_output text,
    structured_output jsonb,
    check_result jsonb,
    check_verdict text,
    session_id uuid,
    input_tokens int8 NOT NULL DEFAULT 0,
    output_tokens int8 NOT NULL DEFAULT 0,
    reasoning_tokens int8 NOT NULL DEFAULT 0,
    cache_read_tokens int8 NOT NULL DEFAULT 0,
    cache_write_tokens int8 NOT NULL DEFAULT 0,
    cost_usd numeric(12,6) NOT NULL DEFAULT '0',
    duration_seconds float8,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_task_attempts PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.task_attempts (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    task_id uuid NOT NULL,
    attempt int4 NOT NULL,
    status public.attempt_status NOT NULL DEFAULT 'running',
    agent_output text,
    structured_output jsonb,
    check_result jsonb,
    check_verdict text,
    session_id uuid,
    input_tokens int8 NOT NULL DEFAULT 0,
    output_tokens int8 NOT NULL DEFAULT 0,
    reasoning_tokens int8 NOT NULL DEFAULT 0,
    cache_read_tokens int8 NOT NULL DEFAULT 0,
    cache_write_tokens int8 NOT NULL DEFAULT 0,
    cost_usd numeric(12,6) NOT NULL DEFAULT '0',
    duration_seconds float8,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_task_attempts PRIMARY KEY (id)
);""", "table", "task_attempts", "task_attempts", 4, True),
    DDLStmt("""CREATE TABLE public.task_iterations (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    task_id uuid NOT NULL,
    iteration_index int4 NOT NULL,
    item_value jsonb NOT NULL DEFAULT '{}'::jsonb,
    status public.attempt_status NOT NULL DEFAULT 'running',
    output text,
    structured_output jsonb,
    check_results jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    CONSTRAINT pk_task_iterations PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.task_iterations (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    task_id uuid NOT NULL,
    iteration_index int4 NOT NULL,
    item_value jsonb NOT NULL DEFAULT '{}'::jsonb,
    status public.attempt_status NOT NULL DEFAULT 'running',
    output text,
    structured_output jsonb,
    check_results jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    CONSTRAINT pk_task_iterations PRIMARY KEY (id)
);""", "table", "task_iterations", "task_iterations", 4, True),
    DDLStmt("""CREATE TABLE public.events (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid,
    task_id uuid,
    source text NOT NULL DEFAULT 'internal',
    event_type text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}',
    idempotency_key text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_events PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.events (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid,
    task_id uuid,
    source text NOT NULL DEFAULT 'internal',
    event_type text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}',
    idempotency_key text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_events PRIMARY KEY (id)
);""", "table", "events", "events", 4, True),
    DDLStmt("""CREATE TABLE public.overseer_workflow_status (
    workflow_id uuid NOT NULL,
    current_step text NOT NULL,
    health public.workflow_health NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_overseer_workflow_status PRIMARY KEY (workflow_id)
);""", """CREATE TABLE IF NOT EXISTS public.overseer_workflow_status (
    workflow_id uuid NOT NULL,
    current_step text NOT NULL,
    health public.workflow_health NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_overseer_workflow_status PRIMARY KEY (workflow_id)
);""", "table", "overseer_workflow_status", "overseer_workflow_status", 4, True),
    DDLStmt("""CREATE TABLE public.assumptions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    text text NOT NULL,
    scope public.assumption_scope NOT NULL,
    inbox_item_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_assumptions PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.assumptions (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    run_id uuid NOT NULL,
    text text NOT NULL,
    scope public.assumption_scope NOT NULL,
    inbox_item_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_assumptions PRIMARY KEY (id)
);""", "table", "assumptions", "assumptions", 4, True),
    DDLStmt("""CREATE TABLE public.context_diffs (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    attempt_id uuid NOT NULL,
    pre_refinement text NOT NULL,
    refinement_diff text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_context_diffs PRIMARY KEY (id)
);""", """CREATE TABLE IF NOT EXISTS public.context_diffs (
    id uuid NOT NULL DEFAULT uuid_generate_v7(),
    attempt_id uuid NOT NULL,
    pre_refinement text NOT NULL,
    refinement_diff text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_context_diffs PRIMARY KEY (id)
);""", "table", "context_diffs", "context_diffs", 4, True),
    DDLStmt("ALTER TABLE public.runs ADD CONSTRAINT fk_runs_created_by FOREIGN KEY (created_by) REFERENCES public.principals (id) ON DELETE RESTRICT;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_runs_created_by'
    AND conrelid = 'public.runs'::regclass
  ) THEN
    ALTER TABLE public.runs ADD CONSTRAINT fk_runs_created_by FOREIGN KEY (created_by) REFERENCES public.principals (id) ON DELETE RESTRICT;
  END IF;
END $$;""", "fk", "fk_runs_created_by", "runs", 6, True),
    DDLStmt("ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_parent FOREIGN KEY (parent_task_id) REFERENCES public.tasks (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_tasks_parent'
    AND conrelid = 'public.tasks'::regclass
  ) THEN
    ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_parent FOREIGN KEY (parent_task_id) REFERENCES public.tasks (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_tasks_parent", "tasks", 6, True),
    DDLStmt("ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_tasks_run'
    AND conrelid = 'public.tasks'::regclass
  ) THEN
    ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_tasks_run", "tasks", 6, True),
    DDLStmt("ALTER TABLE public.transcripts ADD CONSTRAINT fk_transcripts_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE RESTRICT;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_transcripts_run'
    AND conrelid = 'public.transcripts'::regclass
  ) THEN
    ALTER TABLE public.transcripts ADD CONSTRAINT fk_transcripts_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE RESTRICT;
  END IF;
END $$;""", "fk", "fk_transcripts_run", "transcripts", 6, True),
    DDLStmt("ALTER TABLE public.notepad_entries ADD CONSTRAINT fk_notepad_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE RESTRICT;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_notepad_run'
    AND conrelid = 'public.notepad_entries'::regclass
  ) THEN
    ALTER TABLE public.notepad_entries ADD CONSTRAINT fk_notepad_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE RESTRICT;
  END IF;
END $$;""", "fk", "fk_notepad_run", "notepad_entries", 6, True),
    DDLStmt("ALTER TABLE public.inbox_items ADD CONSTRAINT fk_inbox_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_inbox_run'
    AND conrelid = 'public.inbox_items'::regclass
  ) THEN
    ALTER TABLE public.inbox_items ADD CONSTRAINT fk_inbox_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_inbox_run", "inbox_items", 6, True),
    DDLStmt("ALTER TABLE public.decisions ADD CONSTRAINT fk_decisions_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_decisions_run'
    AND conrelid = 'public.decisions'::regclass
  ) THEN
    ALTER TABLE public.decisions ADD CONSTRAINT fk_decisions_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_decisions_run", "decisions", 6, True),
    DDLStmt("ALTER TABLE public.constraints ADD CONSTRAINT fk_constraints_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_constraints_run'
    AND conrelid = 'public.constraints'::regclass
  ) THEN
    ALTER TABLE public.constraints ADD CONSTRAINT fk_constraints_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_constraints_run", "constraints", 6, True),
    DDLStmt("ALTER TABLE public.lessons ADD CONSTRAINT fk_lessons_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_lessons_run'
    AND conrelid = 'public.lessons'::regclass
  ) THEN
    ALTER TABLE public.lessons ADD CONSTRAINT fk_lessons_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_lessons_run", "lessons", 6, True),
    DDLStmt("ALTER TABLE public.run_heartbeats ADD CONSTRAINT fk_run_heartbeats_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_run_heartbeats_run'
    AND conrelid = 'public.run_heartbeats'::regclass
  ) THEN
    ALTER TABLE public.run_heartbeats ADD CONSTRAINT fk_run_heartbeats_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_run_heartbeats_run", "run_heartbeats", 6, True),
    DDLStmt("ALTER TABLE public.knowledge_hashes ADD CONSTRAINT fk_knowledge_hashes_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_knowledge_hashes_run'
    AND conrelid = 'public.knowledge_hashes'::regclass
  ) THEN
    ALTER TABLE public.knowledge_hashes ADD CONSTRAINT fk_knowledge_hashes_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_knowledge_hashes_run", "knowledge_hashes", 6, True),
    DDLStmt("ALTER TABLE public.task_attempts ADD CONSTRAINT fk_task_attempts_task FOREIGN KEY (task_id) REFERENCES public.tasks (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_task_attempts_task'
    AND conrelid = 'public.task_attempts'::regclass
  ) THEN
    ALTER TABLE public.task_attempts ADD CONSTRAINT fk_task_attempts_task FOREIGN KEY (task_id) REFERENCES public.tasks (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_task_attempts_task", "task_attempts", 6, True),
    DDLStmt("ALTER TABLE public.task_iterations ADD CONSTRAINT fk_task_iterations_task FOREIGN KEY (task_id) REFERENCES public.tasks (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_task_iterations_task'
    AND conrelid = 'public.task_iterations'::regclass
  ) THEN
    ALTER TABLE public.task_iterations ADD CONSTRAINT fk_task_iterations_task FOREIGN KEY (task_id) REFERENCES public.tasks (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_task_iterations_task", "task_iterations", 6, True),
    DDLStmt("ALTER TABLE public.events ADD CONSTRAINT fk_events_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE RESTRICT;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_events_run'
    AND conrelid = 'public.events'::regclass
  ) THEN
    ALTER TABLE public.events ADD CONSTRAINT fk_events_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE RESTRICT;
  END IF;
END $$;""", "fk", "fk_events_run", "events", 6, True),
    DDLStmt("ALTER TABLE public.events ADD CONSTRAINT fk_events_task FOREIGN KEY (task_id) REFERENCES public.tasks (id) ON DELETE RESTRICT;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_events_task'
    AND conrelid = 'public.events'::regclass
  ) THEN
    ALTER TABLE public.events ADD CONSTRAINT fk_events_task FOREIGN KEY (task_id) REFERENCES public.tasks (id) ON DELETE RESTRICT;
  END IF;
END $$;""", "fk", "fk_events_task", "events", 6, True),
    DDLStmt("ALTER TABLE public.overseer_workflow_status ADD CONSTRAINT fk_overseer_workflow_status_task FOREIGN KEY (workflow_id) REFERENCES public.tasks (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_overseer_workflow_status_task'
    AND conrelid = 'public.overseer_workflow_status'::regclass
  ) THEN
    ALTER TABLE public.overseer_workflow_status ADD CONSTRAINT fk_overseer_workflow_status_task FOREIGN KEY (workflow_id) REFERENCES public.tasks (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_overseer_workflow_status_task", "overseer_workflow_status", 6, True),
    DDLStmt("ALTER TABLE public.assumptions ADD CONSTRAINT fk_assumptions_inbox FOREIGN KEY (inbox_item_id) REFERENCES public.inbox_items (id) ON DELETE SET NULL;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_assumptions_inbox'
    AND conrelid = 'public.assumptions'::regclass
  ) THEN
    ALTER TABLE public.assumptions ADD CONSTRAINT fk_assumptions_inbox FOREIGN KEY (inbox_item_id) REFERENCES public.inbox_items (id) ON DELETE SET NULL;
  END IF;
END $$;""", "fk", "fk_assumptions_inbox", "assumptions", 6, True),
    DDLStmt("ALTER TABLE public.assumptions ADD CONSTRAINT fk_assumptions_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_assumptions_run'
    AND conrelid = 'public.assumptions'::regclass
  ) THEN
    ALTER TABLE public.assumptions ADD CONSTRAINT fk_assumptions_run FOREIGN KEY (run_id) REFERENCES public.runs (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_assumptions_run", "assumptions", 6, True),
    DDLStmt("ALTER TABLE public.context_diffs ADD CONSTRAINT fk_context_diffs_attempt FOREIGN KEY (attempt_id) REFERENCES public.task_attempts (id) ON DELETE CASCADE;", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_context_diffs_attempt'
    AND conrelid = 'public.context_diffs'::regclass
  ) THEN
    ALTER TABLE public.context_diffs ADD CONSTRAINT fk_context_diffs_attempt FOREIGN KEY (attempt_id) REFERENCES public.task_attempts (id) ON DELETE CASCADE;
  END IF;
END $$;""", "fk", "fk_context_diffs_attempt", "context_diffs", 6, True),
    DDLStmt("ALTER TABLE public.knowledge_hashes ADD CONSTRAINT uq_knowledge_hashes_run_path UNIQUE (run_id, path);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_knowledge_hashes_run_path'
    AND conrelid = 'public.knowledge_hashes'::regclass
  ) THEN
    ALTER TABLE public.knowledge_hashes ADD CONSTRAINT uq_knowledge_hashes_run_path UNIQUE (run_id, path);
  END IF;
END $$;""", "unique", "uq_knowledge_hashes_run_path", "knowledge_hashes", 7, True),
    DDLStmt("ALTER TABLE public.task_attempts ADD CONSTRAINT uq_task_attempts_task_attempt UNIQUE (task_id, attempt);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_task_attempts_task_attempt'
    AND conrelid = 'public.task_attempts'::regclass
  ) THEN
    ALTER TABLE public.task_attempts ADD CONSTRAINT uq_task_attempts_task_attempt UNIQUE (task_id, attempt);
  END IF;
END $$;""", "unique", "uq_task_attempts_task_attempt", "task_attempts", 7, True),
    DDLStmt("ALTER TABLE public.task_iterations ADD CONSTRAINT uq_task_iterations_task_index UNIQUE (task_id, iteration_index);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_task_iterations_task_index'
    AND conrelid = 'public.task_iterations'::regclass
  ) THEN
    ALTER TABLE public.task_iterations ADD CONSTRAINT uq_task_iterations_task_index UNIQUE (task_id, iteration_index);
  END IF;
END $$;""", "unique", "uq_task_iterations_task_index", "task_iterations", 7, True),
    DDLStmt("ALTER TABLE public.runs ADD CONSTRAINT chk_runs_counters_non_negative CHECK (total_input_tokens >= 0 AND total_output_tokens >= 0 AND total_reasoning_tokens >= 0 AND total_cache_read_tokens >= 0 AND total_cache_write_tokens >= 0 AND total_cost_usd >= 0);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_runs_counters_non_negative'
    AND conrelid = 'public.runs'::regclass
  ) THEN
    ALTER TABLE public.runs ADD CONSTRAINT chk_runs_counters_non_negative CHECK (total_input_tokens >= 0 AND total_output_tokens >= 0 AND total_reasoning_tokens >= 0 AND total_cache_read_tokens >= 0 AND total_cache_write_tokens >= 0 AND total_cost_usd >= 0);
  END IF;
END $$;""", "check", "chk_runs_counters_non_negative", "runs", 8, True),
    DDLStmt("ALTER TABLE public.tasks ADD CONSTRAINT chk_tasks_name_not_empty CHECK (name <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_tasks_name_not_empty'
    AND conrelid = 'public.tasks'::regclass
  ) THEN
    ALTER TABLE public.tasks ADD CONSTRAINT chk_tasks_name_not_empty CHECK (name <> '');
  END IF;
END $$;""", "check", "chk_tasks_name_not_empty", "tasks", 8, True),
    DDLStmt("ALTER TABLE public.inbox_items ADD CONSTRAINT chk_inbox_items_question_not_empty CHECK (question <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_inbox_items_question_not_empty'
    AND conrelid = 'public.inbox_items'::regclass
  ) THEN
    ALTER TABLE public.inbox_items ADD CONSTRAINT chk_inbox_items_question_not_empty CHECK (question <> '');
  END IF;
END $$;""", "check", "chk_inbox_items_question_not_empty", "inbox_items", 8, True),
    DDLStmt("ALTER TABLE public.decisions ADD CONSTRAINT chk_decisions_choice_not_empty CHECK (choice <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_decisions_choice_not_empty'
    AND conrelid = 'public.decisions'::regclass
  ) THEN
    ALTER TABLE public.decisions ADD CONSTRAINT chk_decisions_choice_not_empty CHECK (choice <> '');
  END IF;
END $$;""", "check", "chk_decisions_choice_not_empty", "decisions", 8, True),
    DDLStmt("ALTER TABLE public.constraints ADD CONSTRAINT chk_constraints_text_not_empty CHECK (text <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_constraints_text_not_empty'
    AND conrelid = 'public.constraints'::regclass
  ) THEN
    ALTER TABLE public.constraints ADD CONSTRAINT chk_constraints_text_not_empty CHECK (text <> '');
  END IF;
END $$;""", "check", "chk_constraints_text_not_empty", "constraints", 8, True),
    DDLStmt("ALTER TABLE public.lessons ADD CONSTRAINT chk_lessons_text_not_empty CHECK (text <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_lessons_text_not_empty'
    AND conrelid = 'public.lessons'::regclass
  ) THEN
    ALTER TABLE public.lessons ADD CONSTRAINT chk_lessons_text_not_empty CHECK (text <> '');
  END IF;
END $$;""", "check", "chk_lessons_text_not_empty", "lessons", 8, True),
    DDLStmt("ALTER TABLE public.knowledge_hashes ADD CONSTRAINT chk_knowledge_hashes_not_empty CHECK (path <> '' AND file_hash <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_knowledge_hashes_not_empty'
    AND conrelid = 'public.knowledge_hashes'::regclass
  ) THEN
    ALTER TABLE public.knowledge_hashes ADD CONSTRAINT chk_knowledge_hashes_not_empty CHECK (path <> '' AND file_hash <> '');
  END IF;
END $$;""", "check", "chk_knowledge_hashes_not_empty", "knowledge_hashes", 8, True),
    DDLStmt("ALTER TABLE public.task_attempts ADD CONSTRAINT chk_task_attempts_counters_non_negative CHECK (attempt >= 1 AND input_tokens >= 0 AND output_tokens >= 0 AND reasoning_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND cost_usd >= 0);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_task_attempts_counters_non_negative'
    AND conrelid = 'public.task_attempts'::regclass
  ) THEN
    ALTER TABLE public.task_attempts ADD CONSTRAINT chk_task_attempts_counters_non_negative CHECK (attempt >= 1 AND input_tokens >= 0 AND output_tokens >= 0 AND reasoning_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND cost_usd >= 0);
  END IF;
END $$;""", "check", "chk_task_attempts_counters_non_negative", "task_attempts", 8, True),
    DDLStmt("ALTER TABLE public.task_iterations ADD CONSTRAINT chk_task_iterations_index_non_negative CHECK (iteration_index >= 0);", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_task_iterations_index_non_negative'
    AND conrelid = 'public.task_iterations'::regclass
  ) THEN
    ALTER TABLE public.task_iterations ADD CONSTRAINT chk_task_iterations_index_non_negative CHECK (iteration_index >= 0);
  END IF;
END $$;""", "check", "chk_task_iterations_index_non_negative", "task_iterations", 8, True),
    DDLStmt("ALTER TABLE public.overseer_workflow_status ADD CONSTRAINT chk_overseer_workflow_status_step_not_empty CHECK (current_step <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_overseer_workflow_status_step_not_empty'
    AND conrelid = 'public.overseer_workflow_status'::regclass
  ) THEN
    ALTER TABLE public.overseer_workflow_status ADD CONSTRAINT chk_overseer_workflow_status_step_not_empty CHECK (current_step <> '');
  END IF;
END $$;""", "check", "chk_overseer_workflow_status_step_not_empty", "overseer_workflow_status", 8, True),
    DDLStmt("ALTER TABLE public.assumptions ADD CONSTRAINT chk_assumptions_text_not_empty CHECK (text <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_assumptions_text_not_empty'
    AND conrelid = 'public.assumptions'::regclass
  ) THEN
    ALTER TABLE public.assumptions ADD CONSTRAINT chk_assumptions_text_not_empty CHECK (text <> '');
  END IF;
END $$;""", "check", "chk_assumptions_text_not_empty", "assumptions", 8, True),
    DDLStmt("ALTER TABLE public.context_diffs ADD CONSTRAINT chk_context_diffs_not_empty CHECK (pre_refinement <> '');", """DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_context_diffs_not_empty'
    AND conrelid = 'public.context_diffs'::regclass
  ) THEN
    ALTER TABLE public.context_diffs ADD CONSTRAINT chk_context_diffs_not_empty CHECK (pre_refinement <> '');
  END IF;
END $$;""", "check", "chk_context_diffs_not_empty", "context_diffs", 8, True),
    DDLStmt("CREATE INDEX idx_runs_config_snapshot_gin ON public.runs USING gin (config_snapshot);", "CREATE INDEX IF NOT EXISTS idx_runs_config_snapshot_gin ON public.runs USING gin (config_snapshot);", "index", "idx_runs_config_snapshot_gin", "runs", 9, True),
    DDLStmt("CREATE INDEX idx_runs_created_by ON public.runs (created_by);", "CREATE INDEX IF NOT EXISTS idx_runs_created_by ON public.runs (created_by);", "index", "idx_runs_created_by", "runs", 9, True),
    DDLStmt("CREATE INDEX idx_tasks_config_gin ON public.tasks USING gin (config);", "CREATE INDEX IF NOT EXISTS idx_tasks_config_gin ON public.tasks USING gin (config);", "index", "idx_tasks_config_gin", "tasks", 9, True),
    DDLStmt("CREATE INDEX idx_tasks_parent_id ON public.tasks (parent_task_id);", "CREATE INDEX IF NOT EXISTS idx_tasks_parent_id ON public.tasks (parent_task_id);", "index", "idx_tasks_parent_id", "tasks", 9, True),
    DDLStmt("CREATE INDEX idx_tasks_run_id ON public.tasks (run_id);", "CREATE INDEX IF NOT EXISTS idx_tasks_run_id ON public.tasks (run_id);", "index", "idx_tasks_run_id", "tasks", 9, True),
    DDLStmt("CREATE INDEX idx_transcripts_created_at_brin ON public.transcripts USING brin (created_at);", "CREATE INDEX IF NOT EXISTS idx_transcripts_created_at_brin ON public.transcripts USING brin (created_at);", "index", "idx_transcripts_created_at_brin", "transcripts", 9, True),
    DDLStmt("CREATE INDEX idx_transcripts_run ON public.transcripts (run_id);", "CREATE INDEX IF NOT EXISTS idx_transcripts_run ON public.transcripts (run_id);", "index", "idx_transcripts_run", "transcripts", 9, True),
    DDLStmt("CREATE INDEX idx_transcripts_session ON public.transcripts (session_id, turn);", "CREATE INDEX IF NOT EXISTS idx_transcripts_session ON public.transcripts (session_id, turn);", "index", "idx_transcripts_session", "transcripts", 9, True),
    DDLStmt("CREATE INDEX idx_transcripts_tokens_gin ON public.transcripts USING gin (tokens);", "CREATE INDEX IF NOT EXISTS idx_transcripts_tokens_gin ON public.transcripts USING gin (tokens);", "index", "idx_transcripts_tokens_gin", "transcripts", 9, True),
    DDLStmt("CREATE INDEX idx_transcripts_tool_calls_gin ON public.transcripts USING gin (tool_calls);", "CREATE INDEX IF NOT EXISTS idx_transcripts_tool_calls_gin ON public.transcripts USING gin (tool_calls);", "index", "idx_transcripts_tool_calls_gin", "transcripts", 9, True),
    DDLStmt("CREATE INDEX idx_notepad_created_at_brin ON public.notepad_entries USING brin (created_at);", "CREATE INDEX IF NOT EXISTS idx_notepad_created_at_brin ON public.notepad_entries USING brin (created_at);", "index", "idx_notepad_created_at_brin", "notepad_entries", 9, True),
    DDLStmt("CREATE INDEX idx_notepad_run ON public.notepad_entries (run_id);", "CREATE INDEX IF NOT EXISTS idx_notepad_run ON public.notepad_entries (run_id);", "index", "idx_notepad_run", "notepad_entries", 9, True),
    DDLStmt("CREATE INDEX idx_inbox_options_gin ON public.inbox_items USING gin (options);", "CREATE INDEX IF NOT EXISTS idx_inbox_options_gin ON public.inbox_items USING gin (options);", "index", "idx_inbox_options_gin", "inbox_items", 9, True),
    DDLStmt("CREATE INDEX idx_inbox_run_pending ON public.inbox_items (run_id, status, created_at);", "CREATE INDEX IF NOT EXISTS idx_inbox_run_pending ON public.inbox_items (run_id, status, created_at);", "index", "idx_inbox_run_pending", "inbox_items", 9, True),
    DDLStmt("CREATE INDEX idx_inbox_tags_gin ON public.inbox_items USING gin (tags);", "CREATE INDEX IF NOT EXISTS idx_inbox_tags_gin ON public.inbox_items USING gin (tags);", "index", "idx_inbox_tags_gin", "inbox_items", 9, True),
    DDLStmt("CREATE INDEX idx_decisions_run ON public.decisions (run_id);", "CREATE INDEX IF NOT EXISTS idx_decisions_run ON public.decisions (run_id);", "index", "idx_decisions_run", "decisions", 9, True),
    DDLStmt("CREATE INDEX idx_constraints_args_gin ON public.constraints USING gin (args);", "CREATE INDEX IF NOT EXISTS idx_constraints_args_gin ON public.constraints USING gin (args);", "index", "idx_constraints_args_gin", "constraints", 9, True),
    DDLStmt("CREATE INDEX idx_constraints_run ON public.constraints (run_id);", "CREATE INDEX IF NOT EXISTS idx_constraints_run ON public.constraints (run_id);", "index", "idx_constraints_run", "constraints", 9, True),
    DDLStmt("CREATE INDEX idx_lessons_relevance_tags_gin ON public.lessons USING gin (relevance_tags);", "CREATE INDEX IF NOT EXISTS idx_lessons_relevance_tags_gin ON public.lessons USING gin (relevance_tags);", "index", "idx_lessons_relevance_tags_gin", "lessons", 9, True),
    DDLStmt("CREATE INDEX idx_lessons_run ON public.lessons (run_id);", "CREATE INDEX IF NOT EXISTS idx_lessons_run ON public.lessons (run_id);", "index", "idx_lessons_run", "lessons", 9, True),
    DDLStmt("CREATE INDEX idx_lessons_source_files_gin ON public.lessons USING gin (source_files);", "CREATE INDEX IF NOT EXISTS idx_lessons_source_files_gin ON public.lessons USING gin (source_files);", "index", "idx_lessons_source_files_gin", "lessons", 9, True),
    DDLStmt("CREATE INDEX idx_run_heartbeats_run_id ON public.run_heartbeats (run_id);", "CREATE INDEX IF NOT EXISTS idx_run_heartbeats_run_id ON public.run_heartbeats (run_id);", "index", "idx_run_heartbeats_run_id", "run_heartbeats", 9, True),
    DDLStmt("CREATE INDEX idx_knowledge_hashes_run ON public.knowledge_hashes (run_id);", "CREATE INDEX IF NOT EXISTS idx_knowledge_hashes_run ON public.knowledge_hashes (run_id);", "index", "idx_knowledge_hashes_run", "knowledge_hashes", 9, True),
    DDLStmt("CREATE INDEX idx_task_attempts_check_result_gin ON public.task_attempts USING gin (check_result);", "CREATE INDEX IF NOT EXISTS idx_task_attempts_check_result_gin ON public.task_attempts USING gin (check_result);", "index", "idx_task_attempts_check_result_gin", "task_attempts", 9, True),
    DDLStmt("CREATE INDEX idx_task_attempts_structured_output_gin ON public.task_attempts USING gin (structured_output);", "CREATE INDEX IF NOT EXISTS idx_task_attempts_structured_output_gin ON public.task_attempts USING gin (structured_output);", "index", "idx_task_attempts_structured_output_gin", "task_attempts", 9, True),
    DDLStmt("CREATE INDEX idx_task_attempts_task_id ON public.task_attempts (task_id);", "CREATE INDEX IF NOT EXISTS idx_task_attempts_task_id ON public.task_attempts (task_id);", "index", "idx_task_attempts_task_id", "task_attempts", 9, True),
    DDLStmt("CREATE INDEX idx_task_iterations_check_results_gin ON public.task_iterations USING gin (check_results);", "CREATE INDEX IF NOT EXISTS idx_task_iterations_check_results_gin ON public.task_iterations USING gin (check_results);", "index", "idx_task_iterations_check_results_gin", "task_iterations", 9, True),
    DDLStmt("CREATE INDEX idx_task_iterations_item_value_gin ON public.task_iterations USING gin (item_value);", "CREATE INDEX IF NOT EXISTS idx_task_iterations_item_value_gin ON public.task_iterations USING gin (item_value);", "index", "idx_task_iterations_item_value_gin", "task_iterations", 9, True),
    DDLStmt("CREATE INDEX idx_task_iterations_structured_output_gin ON public.task_iterations USING gin (structured_output);", "CREATE INDEX IF NOT EXISTS idx_task_iterations_structured_output_gin ON public.task_iterations USING gin (structured_output);", "index", "idx_task_iterations_structured_output_gin", "task_iterations", 9, True),
    DDLStmt("CREATE INDEX idx_task_iterations_task_id ON public.task_iterations (task_id);", "CREATE INDEX IF NOT EXISTS idx_task_iterations_task_id ON public.task_iterations (task_id);", "index", "idx_task_iterations_task_id", "task_iterations", 9, True),
    DDLStmt("CREATE INDEX idx_events_created_at_brin ON public.events USING brin (created_at);", "CREATE INDEX IF NOT EXISTS idx_events_created_at_brin ON public.events USING brin (created_at);", "index", "idx_events_created_at_brin", "events", 9, True),
    DDLStmt("CREATE INDEX idx_events_data_gin ON public.events USING gin (data);", "CREATE INDEX IF NOT EXISTS idx_events_data_gin ON public.events USING gin (data);", "index", "idx_events_data_gin", "events", 9, True),
    DDLStmt("CREATE UNIQUE INDEX idx_events_idempotency_key ON public.events (idempotency_key) WHERE idempotency_key IS NOT NULL;", "CREATE UNIQUE INDEX IF NOT EXISTS idx_events_idempotency_key ON public.events (idempotency_key) WHERE idempotency_key IS NOT NULL;", "index", "idx_events_idempotency_key", "events", 9, True),
    DDLStmt("CREATE INDEX idx_events_run_created ON public.events (run_id, created_at DESC);", "CREATE INDEX IF NOT EXISTS idx_events_run_created ON public.events (run_id, created_at DESC);", "index", "idx_events_run_created", "events", 9, True),
    DDLStmt("CREATE INDEX idx_events_source_created ON public.events (source, created_at DESC);", "CREATE INDEX IF NOT EXISTS idx_events_source_created ON public.events (source, created_at DESC);", "index", "idx_events_source_created", "events", 9, True),
    DDLStmt("CREATE INDEX idx_events_task_id ON public.events (task_id);", "CREATE INDEX IF NOT EXISTS idx_events_task_id ON public.events (task_id);", "index", "idx_events_task_id", "events", 9, True),
    DDLStmt("CREATE INDEX idx_events_type_created ON public.events (event_type, created_at DESC);", "CREATE INDEX IF NOT EXISTS idx_events_type_created ON public.events (event_type, created_at DESC);", "index", "idx_events_type_created", "events", 9, True),
    DDLStmt("CREATE INDEX idx_overseer_workflow_status_workflow_id ON public.overseer_workflow_status (workflow_id);", "CREATE INDEX IF NOT EXISTS idx_overseer_workflow_status_workflow_id ON public.overseer_workflow_status (workflow_id);", "index", "idx_overseer_workflow_status_workflow_id", "overseer_workflow_status", 9, True),
    DDLStmt("CREATE INDEX idx_assumptions_inbox ON public.assumptions (inbox_item_id);", "CREATE INDEX IF NOT EXISTS idx_assumptions_inbox ON public.assumptions (inbox_item_id);", "index", "idx_assumptions_inbox", "assumptions", 9, True),
    DDLStmt("CREATE INDEX idx_assumptions_run ON public.assumptions (run_id);", "CREATE INDEX IF NOT EXISTS idx_assumptions_run ON public.assumptions (run_id);", "index", "idx_assumptions_run", "assumptions", 9, True),
    DDLStmt("CREATE INDEX idx_context_diffs_attempt ON public.context_diffs (attempt_id);", "CREATE INDEX IF NOT EXISTS idx_context_diffs_attempt ON public.context_diffs (attempt_id);", "index", "idx_context_diffs_attempt", "context_diffs", 9, True),
    DDLStmt("CREATE TRIGGER deny_mutation BEFORE UPDATE OR DELETE ON public.transcripts FOR EACH ROW EXECUTE FUNCTION public.pgdesign_deny_mutation();", "CREATE OR REPLACE TRIGGER deny_mutation BEFORE UPDATE OR DELETE ON public.transcripts FOR EACH ROW EXECUTE FUNCTION public.pgdesign_deny_mutation();", "append_only_trigger", "transcripts.deny_mutation", "transcripts", 9, True),
    DDLStmt("CREATE TRIGGER deny_mutation BEFORE UPDATE OR DELETE ON public.notepad_entries FOR EACH ROW EXECUTE FUNCTION public.pgdesign_deny_mutation();", "CREATE OR REPLACE TRIGGER deny_mutation BEFORE UPDATE OR DELETE ON public.notepad_entries FOR EACH ROW EXECUTE FUNCTION public.pgdesign_deny_mutation();", "append_only_trigger", "notepad_entries.deny_mutation", "notepad_entries", 9, True),
    DDLStmt("CREATE TRIGGER deny_mutation BEFORE UPDATE OR DELETE ON public.events FOR EACH ROW EXECUTE FUNCTION public.pgdesign_deny_mutation();", "CREATE OR REPLACE TRIGGER deny_mutation BEFORE UPDATE OR DELETE ON public.events FOR EACH ROW EXECUTE FUNCTION public.pgdesign_deny_mutation();", "append_only_trigger", "events.deny_mutation", "events", 9, True),
    DDLStmt("COMMENT ON TABLE public.runs IS 'Top-level run records. One run per intent execution.';", None, "comment", "table.runs", "runs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.runs.intent IS 'The user''s original intent';", None, "comment", "column.runs.intent", "runs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.runs.config_snapshot IS 'Fully resolved configuration: categories, budgets, tool registry names, agent definitions';", None, "comment", "column.runs.config_snapshot", "runs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.runs.created_by IS 'The creating actor''s principal. Historical rows are backfilled to the system principal (the original creator is unknowable).';", None, "comment", "column.runs.created_by", "runs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.runs.total_cost_usd IS 'Best-effort USD from orxtra internal pricing table';", None, "comment", "column.runs.total_cost_usd", "runs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.runs.coherence_summary IS 'Overseer end-of-run assessment of intent fulfillment';", None, "comment", "column.runs.coherence_summary", "runs", 10, True),
    DDLStmt("COMMENT ON TABLE public.tasks IS 'Recursive task hierarchy within a run. Replaces the old workflows + steps tables.';", None, "comment", "table.tasks", "tasks", 10, True),
    DDLStmt("COMMENT ON COLUMN public.tasks.parent_task_id IS 'Parent task for nested task hierarchies';", None, "comment", "column.tasks.parent_task_id", "tasks", 10, True),
    DDLStmt("COMMENT ON COLUMN public.tasks.config IS 'Task configuration';", None, "comment", "column.tasks.config", "tasks", 10, True),
    DDLStmt("COMMENT ON TABLE public.transcripts IS 'Full conversation history per transport session. Immutability enforced by trigger.';", None, "comment", "table.transcripts", "transcripts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.transcripts.session_id IS 'Transport session UUID';", None, "comment", "column.transcripts.session_id", "transcripts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.transcripts.role IS 'user, assistant, or tool_result';", None, "comment", "column.transcripts.role", "transcripts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.transcripts.content IS 'Full content (never truncated)';", None, "comment", "column.transcripts.content", "transcripts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.transcripts.tool_calls IS 'For assistant turns: [{name, input, output}]';", None, "comment", "column.transcripts.tool_calls", "transcripts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.transcripts.tokens IS 'Token usage for this turn';", None, "comment", "column.transcripts.tokens", "transcripts", 10, True),
    DDLStmt("COMMENT ON TABLE public.notepad_entries IS 'Cross-agent context sharing within a run. Immutability enforced by trigger.';", None, "comment", "table.notepad_entries", "notepad_entries", 10, True),
    DDLStmt("COMMENT ON TABLE public.inbox_items IS 'Human inbox. Items created by the Overseer. Tags for triage, five-status lifecycle (pending/answered/skipped/expired/rejected), answer events for wait-for task integration.';", None, "comment", "table.inbox_items", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.decision_type IS 'Decision type that emitted this item (e.g., retry_strategy, budget_reallocation)';", None, "comment", "column.inbox_items.decision_type", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.options IS 'Options considered by the Overseer';", None, "comment", "column.inbox_items.options", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.assumed_option IS 'Which option the Overseer assumed';", None, "comment", "column.inbox_items.assumed_option", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.work_proceeding IS 'What work continues under the assumption';", None, "comment", "column.inbox_items.work_proceeding", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.contradiction_impact IS 'What happens if the human picks differently';", None, "comment", "column.inbox_items.contradiction_impact", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.tags IS 'Framework auto-injects decision_type; Overseer may add free-form tags';", None, "comment", "column.inbox_items.tags", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.answer IS 'Human response text';", None, "comment", "column.inbox_items.answer", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.answer_event IS 'Event name fired when answered, for wait-for tasks to await';", None, "comment", "column.inbox_items.answer_event", "inbox_items", 10, True),
    DDLStmt("COMMENT ON COLUMN public.inbox_items.rejection_reason IS 'Why the human rejected this item (requires re-investigation and a new item)';", None, "comment", "column.inbox_items.rejection_reason", "inbox_items", 10, True),
    DDLStmt("COMMENT ON TABLE public.decisions IS 'Overseer decision records. Every decision is recorded with its type, choice, and rationale.';", None, "comment", "table.decisions", "decisions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.decisions.decision_type IS 'What kind of decision (e.g., retry_strategy, budget_reallocation)';", None, "comment", "column.decisions.decision_type", "decisions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.decisions.choice IS 'Decision choice';", None, "comment", "column.decisions.choice", "decisions", 10, True),
    DDLStmt("COMMENT ON TABLE public.constraints IS 'Constraints accumulated by the Overseer. Mechanical ones are checked by the scheduler after each task.';", None, "comment", "table.constraints", "constraints", 10, True),
    DDLStmt("COMMENT ON COLUMN public.constraints.text IS 'Human-readable description of the constraint';", None, "comment", "column.constraints.text", "constraints", 10, True),
    DDLStmt("COMMENT ON COLUMN public.constraints.kind IS 'Constraint kind from vocabulary (mechanical) or free-form identifier (advisory)';", None, "comment", "column.constraints.kind", "constraints", 10, True),
    DDLStmt("COMMENT ON COLUMN public.constraints.args IS 'Structured arguments for mechanical constraints (e.g., {glob: ''src/**/*.py''})';", None, "comment", "column.constraints.args", "constraints", 10, True),
    DDLStmt("COMMENT ON TABLE public.lessons IS 'Cross-run knowledge base. Primary store for learned facts.';", None, "comment", "table.lessons", "lessons", 10, True),
    DDLStmt("COMMENT ON COLUMN public.lessons.relevance_tags IS 'Relevance tags for flat SQL queries';", None, "comment", "column.lessons.relevance_tags", "lessons", 10, True),
    DDLStmt("COMMENT ON COLUMN public.lessons.permanent IS 'True for consumer knowledge; never expires';", None, "comment", "column.lessons.permanent", "lessons", 10, True),
    DDLStmt("COMMENT ON COLUMN public.lessons.source_files IS 'File paths for git-based staleness detection (any file changing flags the lesson as potentially stale)';", None, "comment", "column.lessons.source_files", "lessons", 10, True),
    DDLStmt("COMMENT ON TABLE public.run_heartbeats IS 'Heartbeat tracking for active runs.';", None, "comment", "table.run_heartbeats", "run_heartbeats", 10, True),
    DDLStmt("COMMENT ON TABLE public.knowledge_hashes IS 'Content hashes for knowledge files. Used to skip reloading unchanged files.';", None, "comment", "table.knowledge_hashes", "knowledge_hashes", 10, True),
    DDLStmt("COMMENT ON COLUMN public.knowledge_hashes.path IS 'Filesystem path of the knowledge file';", None, "comment", "column.knowledge_hashes.path", "knowledge_hashes", 10, True),
    DDLStmt("COMMENT ON COLUMN public.knowledge_hashes.file_hash IS 'SHA-256 content hash';", None, "comment", "column.knowledge_hashes.file_hash", "knowledge_hashes", 10, True),
    DDLStmt("COMMENT ON TABLE public.task_attempts IS 'Per-attempt results for tasks. Retries create new rows, never overwrite.';", None, "comment", "table.task_attempts", "task_attempts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_attempts.attempt IS 'Attempt number';", None, "comment", "column.task_attempts.attempt", "task_attempts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_attempts.agent_output IS 'Full text output from the agent (never truncated)';", None, "comment", "column.task_attempts.agent_output", "task_attempts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_attempts.structured_output IS 'Validated JSON if output_schema was set on the task';", None, "comment", "column.task_attempts.structured_output", "task_attempts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_attempts.check_result IS 'Check runner result';", None, "comment", "column.task_attempts.check_result", "task_attempts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_attempts.check_verdict IS 'Check verdict text';", None, "comment", "column.task_attempts.check_verdict", "task_attempts", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_attempts.session_id IS 'Transport session UUID for this attempt';", None, "comment", "column.task_attempts.session_id", "task_attempts", 10, True),
    DDLStmt("COMMENT ON TABLE public.task_iterations IS 'Per-iteration state for iterating tasks.';", None, "comment", "table.task_iterations", "task_iterations", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_iterations.iteration_index IS 'Zero-based iteration index';", None, "comment", "column.task_iterations.iteration_index", "task_iterations", 10, True),
    DDLStmt("COMMENT ON COLUMN public.task_iterations.item_value IS 'The item being iterated over';", None, "comment", "column.task_iterations.item_value", "task_iterations", 10, True),
    DDLStmt("COMMENT ON TABLE public.events IS 'Append-only audit log. Immutability enforced by trigger.';", None, "comment", "table.events", "events", 10, True),
    DDLStmt("COMMENT ON COLUMN public.events.source IS 'Event source: internal (scheduler/trace) or external (MCP/CLI)';", None, "comment", "column.events.source", "events", 10, True),
    DDLStmt("COMMENT ON COLUMN public.events.event_type IS 'e.g. run.started, task.status_changed, inbox.item_answered';", None, "comment", "column.events.event_type", "events", 10, True),
    DDLStmt("COMMENT ON COLUMN public.events.data IS 'Event-specific payload';", None, "comment", "column.events.data", "events", 10, True),
    DDLStmt("COMMENT ON COLUMN public.events.idempotency_key IS 'Caller-supplied dedup key; partial unique index prevents duplicate storage and dispatch';", None, "comment", "column.events.idempotency_key", "events", 10, True),
    DDLStmt("COMMENT ON TABLE public.overseer_workflow_status IS 'Overseer view of workflow health. Overwritten as the Overseer updates its assessment.';", None, "comment", "table.overseer_workflow_status", "overseer_workflow_status", 10, True),
    DDLStmt("COMMENT ON COLUMN public.overseer_workflow_status.workflow_id IS 'Workflow task identifier';", None, "comment", "column.overseer_workflow_status.workflow_id", "overseer_workflow_status", 10, True),
    DDLStmt("COMMENT ON TABLE public.assumptions IS 'Assumptions made by the Overseer when information is unavailable.';", None, "comment", "table.assumptions", "assumptions", 10, True),
    DDLStmt("COMMENT ON COLUMN public.assumptions.inbox_item_id IS 'Inbox item created for this assumption (if escalated)';", None, "comment", "column.assumptions.inbox_item_id", "assumptions", 10, True),
    DDLStmt("COMMENT ON TABLE public.context_diffs IS 'Pre- and post-Overseer-refinement context per task attempt.';", None, "comment", "table.context_diffs", "context_diffs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.context_diffs.pre_refinement IS 'Mechanically assembled context (layers 1+2)';", None, "comment", "column.context_diffs.pre_refinement", "context_diffs", 10, True),
    DDLStmt("COMMENT ON COLUMN public.context_diffs.refinement_diff IS 'Unified diff of Overseer''s context changes';", None, "comment", "column.context_diffs.refinement_diff", "context_diffs", 10, True),
    DDLStmt("CREATE TRIGGER trg_notify_event AFTER INSERT ON public.events FOR EACH ROW EXECUTE FUNCTION public.notify_orxtra_event();", "CREATE OR REPLACE TRIGGER trg_notify_event AFTER INSERT ON public.events FOR EACH ROW EXECUTE FUNCTION public.notify_orxtra_event();", "trigger", "trg_notify_event", "events", 17, True),
]

TABLE_NAMES: Final[tuple[str, ...]] = ("runs", "tasks", "transcripts", "notepad_entries", "inbox_items", "decisions", "constraints", "lessons", "run_heartbeats", "knowledge_hashes", "task_attempts", "task_iterations", "events", "overseer_workflow_status", "assumptions", "context_diffs")
